### ISSUE TITLE
Calculate estimated Solar generation

### ISSUE THREAD

**Issue by fjebaker** [aimlac-7564616D/models#2]

**Comment by lballisat** [comment]
Mapping between APIs



SLIMJaB API field | Type | Description | MetOffice API equivalent field
-- | -- | -- | --
U | Int | Solar UV index | uvIndex
W | int | Significant weather code | significantWeatherCode
V | int or string | visibility | visibility
T | float | Screen Temperature | screenTemperature
S | float | Wind speed | windSpeed10m
P | float | Mean sea pressure in hPa | mslp
Pp | float | Precipitation probability | probOfPrecipitation
H | float | Screen relative humidity | screenRelativeHumidity
G | float | wind gust | max10mWindGust
F | float | Feels like temperature | feelsLikeTemperature
D | string | wind direction in compass points | windDirectionFrom10m
$ | int | number of minutes after midnight | time
