### ISSUE TITLE
Models are outdated

### ISSUE THREAD

**Issue by fjebaker** [aimlac-7564616D/models#22]
Un-pickling some of the ML models:
```
UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.23.2 
  when using version 1.0.2. This might lead to breaking code or invalid results. Use 
  at your own risk. For more info please refer to:
  https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
```

Do we back date our environment, or should we try to update new models?

**Comment by dingsheng-ong** [comment]
As a simple workaround, I suggest that we just re-create the models and re-use the parameters, it is not worth changing our environment for a few models that may be replaced in the future. I updated the three models' pickle files, so they should no longer produce any warnings.

[patch.zip](https://github.com/aimlac-7564616D/models/files/8318079/patch.zip)

**Comment by fjebaker** [comment]
Excellent! Then we only need to address
- #24 

Closing.
